export const beats = [
  {
    type: "stage",
    text: "Stage black. No giant logo. No product carousel. Just a cursor blinking on an old terminal.",
  },
  { type: "say", text: "Good evening." },
  { type: "say", text: "I want to start somewhere slightly strange." },
  { type: "say", text: "Not with artificial intelligence." },
  { type: "say", text: "Not with crypto." },
  { type: "say", text: "Not with LITHOS." },
  { type: "say", text: "I want to start in Caloundra." },
  {
    type: "say",
    text: "Around 2016, leading into 2017, I was trying to work out what I wanted to make.",
  },
  { type: "say", text: "For a while, I wanted to be a photographer." },
  { type: "say", text: "Then I wanted to make horror movies." },
  { type: "say", text: "Link Morgan helped me explore that world." },
  {
    type: "say",
    text: "Cameras. Images. Atmosphere. Telling stories by deciding what somebody could see—and what remained outside the frame.",
  },
  { type: "say", text: "Then Josh Hills helped me get interested in 3D modelling." },
  {
    type: "say",
    text: "And I discovered this enormous, messy, brilliant place called Thingiverse.",
  },
  { type: "screen", id: "thingiverse" },
  { type: "say", text: "People made things.", emphasis: "things" },
  { type: "say", text: "That sounds ridiculously obvious." },
  { type: "say", text: "But think about what that meant." },
  { type: "say", text: "Somebody, somewhere, had an idea." },
  { type: "say", text: "They modelled it." },
  { type: "say", text: "They uploaded the files." },
  { type: "say", text: "Another person downloaded it." },
  { type: "say", text: "They printed it." },
  { type: "say", text: "Maybe it didn't work." },
  { type: "say", text: "So they changed it." },
  { type: "say", text: "They remixed it." },
  { type: "say", text: "Uploaded their version." },
  { type: "say", text: "Someone else found that." },
  {
    type: "say",
    text: "And suddenly an idea wasn't travelling in a straight line anymore.",
  },
  { type: "say", text: "It had ancestry." },
  { type: "say", text: "It had branches." },
  { type: "say", text: "It had a community around it." },
  { type: "say", text: "I didn't have the vocabulary for that then." },
  { type: "say", text: "I certainly wasn't sitting there going:" },
  {
    type: "quote",
    text: "Excellent. This is clearly the beginning of a distributed object-lineage operating system.",
  },
  { type: "pause" },
  { type: "say", text: "I was probably just trying to make cool shit." },
  { type: "say", text: "And I think that's important." },
  {
    type: "say",
    text: "Because ten years later, we're surrounded by extraordinary technology.",
  },
  { type: "say", text: "Models can reason." },
  { type: "say", text: "Agents can operate computers." },
  { type: "say", text: "Blockchains can coordinate ownership and state." },
  { type: "say", text: "Computers can manufacture physical objects." },
  {
    type: "say",
    text: "A teenager can download Blender tonight and start building a world.",
  },
  { type: "say", text: "But our systems still have an enormous problem." },
  { type: "say", text: "They don't know how to belong together.", strong: true },
  { type: "list", items: ["applications", "accounts", "wallets", "subscriptions", "files", "chats", "agents", "repositories", "credentials", "devices", "clouds"] },
  { type: "say", text: "And increasingly, autonomous software operating between all of them." },
  { type: "say", text: "We keep adding intelligence." },
  { type: "say", text: "But intelligence without relationships becomes another silo." },
  { type: "say", text: "So LITHOS starts somewhere else." },
  { type: "say", text: "Not:" },
  { type: "say", text: "What can AI do?", strong: true },
  { type: "say", text: "But:" },
  { type: "say", text: "Where does this thing belong?", strong: true },
  { type: "screen", id: "belong" },
  { type: "say", text: "We call the environment LITHOS//OS." },
  {
    type: "say",
    text: "But “OS” doesn't mean we're trying to replace Windows, macOS, Linux or your phone.",
  },
  { type: "say", text: "Those systems already understand machines extraordinarily well." },
  { type: "say", text: "We are interested in the layer above them." },
  { type: "say", text: "The layer that understands relationships.", emphasis: "relationships" },
  { type: "say", text: "Who is asking?" },
  { type: "say", text: "Where are they?" },
  { type: "say", text: "What are they touching?" },
  { type: "say", text: "What are they allowed to touch?" },
  { type: "say", text: "Which machine is acting?" },
  { type: "say", text: "What happened?" },
  { type: "say", text: "And what comes home afterward?" },
  { type: "say", text: "That sounds boring." },
  { type: "say", text: "Good." },
  { type: "say", text: "Trust infrastructure should occasionally be boring." },
  { type: "say", text: "The interesting part is what becomes possible once it exists." },
  { type: "say", text: "Imagine opening a project." },
  { type: "say", text: "Not opening twelve applications associated with a project." },
  { type: "say", text: "Opening the actual project.", emphasis: "actual project" },
  {
    type: "list",
    items: [
      "Its designs are there.",
      "Its Git repository is there.",
      "Its conversations are there.",
      "Its Blender models are there.",
      "Its people are there.",
      "Its agents are there.",
      "Its decisions are there.",
      "Its previous failures are there.",
    ],
  },
  {
    type: "say",
    text: "And if some component has verifiable provenance or ownership that benefits from a ledger, that evidence can be there too.",
  },
  { type: "say", text: "Not because everything needs to become crypto." },
  { type: "say", text: "It absolutely doesn't." },
  { type: "say", text: "A blockchain is not seasoning." },
  { type: "pause" },
  { type: "say", text: "Please stop putting it on everything." },
  { type: "screen", id: "toaster" },
  { type: "say", text: "But sometimes shared state matters." },
  { type: "say", text: "Sometimes provenance matters." },
  {
    type: "say",
    text: "Sometimes independent parties need to verify something without one company becoming the permanent owner of everybody else's history.",
  },
  { type: "say", text: "That is where networks such as Sui become interesting to us." },
  { type: "say", text: "As infrastructure." },
  { type: "say", text: "Not religion." },
  { type: "say", text: "LITHOS has another rule:" },
  { type: "say", text: "Providers supply capability, never sovereignty.", strong: true },
  { type: "say", text: "Claude can be brilliant." },
  { type: "say", text: "Gemini can be brilliant." },
  { type: "say", text: "Local models can be brilliant." },
  { type: "say", text: "Sui can provide useful primitives." },
  { type: "say", text: "GitHub can hold code." },
  { type: "say", text: "Blender can create geometry." },
  { type: "say", text: "Thingiverse can distribute objects." },
  { type: "say", text: "None of those should become the definition of the human using them." },
  { type: "say", text: "The human remains above the provider." },
  { type: "screen", id: "you" },
  { type: "say", text: "And this is where the old Thingiverse idea comes back." },
  {
    type: "say",
    text: "We call something a Thing when it needs to survive the application that created it.",
    emphasis: "Thing",
  },
  { type: "say", text: "A Thing can have a source." },
  { type: "say", text: "A Thing can have history." },
  { type: "say", text: "A Thing can be forked." },
  { type: "say", text: "A Thing can be remixed." },
  { type: "say", text: "A Thing can become physical." },
  { type: "say", text: "A Thing can fail." },
  { type: "say", text: "And failure shouldn't disappear." },
  { type: "say", text: "In LITHOS, we have another piece of grammar:" },
  { type: "glyph", key: "SCAR", value: "LEARNING" },
  { type: "say", text: "When a thread breaks, we don't pretend it never existed." },
  { type: "say", text: "The scar stays." },
  {
    type: "say",
    text: "Because systems become trustworthy not when they never fail, but when they can explain what happened when they did.",
  },
  { type: "say", text: "Then:" },
  { type: "glyph", key: "WEIGHT", value: "MEMORY" },
  { type: "grammar" },
  { type: "say", text: "The scar preserves the event." },
  { type: "say", text: "The weight preserves its consequence." },
  { type: "say", text: "That changes how the next decision is made." },
  { type: "say", text: "And suddenly we're no longer designing a prettier task manager." },
  {
    type: "say",
    text: "We're designing software that can accumulate experience without pretending experience equals authority.",
  },
  { type: "say", text: "Because there is one final rule." },
  { type: "cursor-only" },
  { type: "glyph", key: "CURSOR", value: "HUMAN" },
  { type: "say", text: "Agents can propose." },
  { type: "say", text: "Agents can search." },
  { type: "say", text: "Agents can build." },
  { type: "say", text: "Agents can route." },
  { type: "say", text: "Agents can remember." },
  { type: "say", text: "Agents can execute within scope." },
  {
    type: "say",
    text: "But when threads collide and something consequential must be chosen:",
  },
  { type: "glyph", key: "KNOT", value: "DECISION" },
  { type: "say", text: "And the human ties the knot." },
  {
    type: "say",
    text: "That distinction matters more as our machines become more capable.",
  },
  {
    type: "say",
    text: "I don't want a future where one giant assistant knows everything about me, owns everything around me and quietly decides everything for me.",
  },
  { type: "say", text: "That's not intelligence." },
  { type: "say", text: "That's dependency with excellent UX." },
  {
    type: "say",
    text: "I want hundreds of capabilities that can enter a place, receive exactly the context they require, perform bounded work, leave a receipt and go home.",
  },
  { type: "say", text: "And I want the interface to make that understandable." },
  {
    type: "say",
    text: "Not through enterprise dashboards covered in fourteen thousand rectangles.",
  },
  { type: "say", text: "Through grammar." },
  { type: "grammar-list" },
  { type: "say", text: "Once you learn six ideas, you should be able to walk through the system." },
  { type: "say", text: "The aesthetic reflects that philosophy too." },
  { type: "say", text: "Yes, there is obsidian." },
  { type: "say", text: "There is glass." },
  { type: "say", text: "There is cyan." },
  { type: "say", text: "There is amber." },
  { type: "say", text: "There is violet." },
  {
    type: "say",
    text: "And probably far too much affection for interfaces from approximately 1997 to 2007.",
  },
  { type: "screen", id: "nudge" },
  {
    type: "say",
    text: "Somewhere, somebody's profile is absolutely going to contain an unnecessarily dramatic status message.",
  },
  { type: "say", text: "But nostalgia isn't the objective." },
  {
    type: "say",
    text: "Those older communities sometimes possessed something modern software polished away.",
  },
  { type: "say", text: "Place.", strong: true },
  { type: "say", text: "Forums felt like places." },
  { type: "say", text: "Game lobbies felt like places." },
  { type: "say", text: "Maker communities felt like workshops." },
  { type: "say", text: "Your weird little corner of the internet felt inhabited." },
  {
    type: "say",
    text: "We want that feeling back without bringing back the insecurity, fragmentation and terrible password practices.",
  },
  {
    type: "say",
    text: "The next internet shouldn't feel like walking through an airport duty-free store forever.",
  },
  { type: "list", items: ["workshops", "benches", "libraries", "studios", "commons", "private rooms", "doors", "locks"] },
  { type: "say", text: "Real locks." },
  { type: "say", text: "Because a door means nothing if software can simply walk through the wall." },
  { type: "pause" },
  { type: "say", text: "So what are we actually building first?" },
  { type: "say", text: "Not the empire." },
  { type: "say", text: "Not the token." },
  { type: "say", text: "Not the cinematic trailer." },
  { type: "say", text: "Not 120 screens explaining what someday might exist." },
  { type: "say", text: "We're building one honest vertical slice." },
  { type: "screen", id: "slice" },
  { type: "say", text: "One human." },
  { type: "say", text: "One place." },
  { type: "say", text: "One useful piece of work." },
  { type: "say", text: "One bounded agent." },
  { type: "say", text: "One visible permission boundary." },
  { type: "say", text: "One receipt proving what actually happened." },
  { type: "say", text: "Then we try to break it." },
  { type: "say", text: "Then somebody else tries to break it." },
  { type: "say", text: "Then we record the scars." },
  { type: "say", text: "Then we improve it." },
  { type: "say", text: "And only then do we add another layer." },
  { type: "say", text: "Because LITHOS isn't interesting if Josh can operate it." },
  { type: "say", text: "Of course I can operate my own mythology." },
  { type: "pause" },
  { type: "say", text: "The test is whether you can enter it.", emphasis: "you" },
  { type: "say", text: "Understand it." },
  { type: "say", text: "Bring something you made." },
  { type: "say", text: "Connect something you trust." },
  { type: "say", text: "Choose an agent you trust." },
  { type: "say", text: "See exactly what it can touch." },
  { type: "say", text: "Make something useful." },
  { type: "say", text: "Take that thing somewhere else." },
  { type: "say", text: "And leave without asking us for permission." },
  { type: "say", text: "That's the dream." },
  {
    type: "say",
    text: "And strangely enough, I think part of it was already sitting there in Caloundra ten years ago.",
  },
  { type: "list", items: ["A camera.", "A horror movie.", "A 3D model.", "A printer.", "A website full of strangers making strange little objects for one another."] },
  { type: "say", text: "I thought I was learning how to make things." },
  { type: "say", text: "I think I was actually learning something larger:" },
  {
    type: "say",
    text: "Things become more valuable when people can carry them forward.",
    strong: true,
  },
  { type: "say", text: "So that's what we're building." },
  { type: "say", text: "Not something that owns everything." },
  { type: "say", text: "Something that lets everything understand where it belongs." },
  { type: "say", text: "Not a machine replacing the person holding the cursor." },
  { type: "say", text: "A machine capable enough to help—" },
  { type: "say", text: "and disciplined enough to let go." },
  { type: "thread" },
  { type: "stage", text: "Someone in the audience laughs." },
  { type: "say", text: "Good." },
  { type: "say", text: "You understand it." },
  { type: "say", text: "Welcome to LITHOS.", strong: true },
  { type: "screen", id: "path" },
  { type: "early" },
];
