import type { Glyph } from "./types.ts";

// ICON//LEXICON — captured, 2 locks + 2 cautions applied.
//
// Lock 1: representation is not identity (see constitution.ts, LAW 06).
// Lock 2: one glyph = one runtime meaning. ↗ (leave-place) is MAP/RENDER only;
//         ⇱ (escalate) is GUARDIAN/RECEIPT only. They never describe the same event.
// Caution 1: `category` is authoritative here. Note `locked-place` vs
//         `guardian-enforced` share the mark 🔒 but are different meanings.
// Caution 2: curated search lives in gazetteer.ts, not in free-text matching.

export const LEXICON: Glyph[] = [
  // ── HUMAN ───────────────────────────────────────────────────────────────
  {
    id: "cursor",
    mark: "👤",
    name: "CURSOR",
    category: "HUMAN",
    meaning: "The human. The one who chooses.",
    surfaces: ["MAP", "RENDER", "PICKER"],
    keywords: ["human", "person", "cursor", "self", "presence", "who"],
  },
  {
    id: "identity",
    mark: "◍",
    name: "IDENTITY",
    category: "HUMAN",
    meaning: "A human identity, independent of any glyph that represents it.",
    surfaces: ["RENDER", "PICKER", "RECEIPT"],
    keywords: ["identity", "fingerprint", "who", "self", "id"],
  },

  // ── PLACE ───────────────────────────────────────────────────────────────
  {
    id: "place-boundary",
    mark: "[ ]",
    name: "PLACE BOUNDARY",
    category: "PLACE",
    meaning: "The boundary of a place. What is inside, and what is not.",
    surfaces: ["MAP", "RENDER", "RECEIPT"],
    keywords: ["boundary", "place", "container", "bracket", "room", "scope"],
  },
  {
    id: "scope",
    mark: "◉",
    name: "SCOPE",
    category: "PLACE",
    meaning: "The extent of a place — how far its authority reaches.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["scope", "boundary", "extent", "reach"],
  },
  {
    id: "commons",
    mark: "🌐",
    name: "COMMONS",
    category: "PLACE",
    meaning: "The shared public place. The web becomes the Commons.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["web", "globe", "commons", "public", "network", "world"],
  },
  {
    id: "building",
    mark: "🏛",
    name: "BUILDING",
    category: "PLACE",
    meaning: "An institutional place with standing.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["building", "org", "institution", "place", "bank"],
  },
  {
    id: "home",
    mark: "⌂",
    name: "HOME",
    category: "PLACE",
    meaning: "The place a human returns to.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["home", "house", "return", "base"],
  },
  {
    id: "locked-place",
    mark: "🔒",
    name: "LOCKED PLACE",
    category: "PLACE",
    meaning: "A place whose boundary is sealed. (Same mark as GUARDIAN-ENFORCED — category disambiguates.)",
    surfaces: ["MAP", "RENDER"],
    keywords: ["locked", "sealed", "closed", "place", "private"],
  },

  // ── THING ───────────────────────────────────────────────────────────────
  {
    id: "node",
    mark: "◈",
    name: "NODE",
    category: "THING",
    meaning: "A Thing that exists in the tree.",
    surfaces: ["MAP", "RENDER", "PICKER"],
    keywords: ["node", "thing", "object", "diamond"],
  },
  {
    id: "repository",
    mark: "⧉",
    name: "REPOSITORY",
    category: "THING",
    meaning: "A versioned Thing that holds work and its history.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["repository", "repo", "github", "git", "code", "thing"],
  },
  {
    id: "branch",
    mark: "🌿",
    name: "BRANCH",
    category: "THING",
    meaning: "A line of growth off a Thing.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["branch", "github", "git", "grow", "line"],
  },
  {
    id: "struct",
    mark: "{ }",
    name: "STRUCTURE",
    category: "THING",
    meaning: "Composed structure — what belongs together.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["braces", "struct", "json", "object", "composition", "code"],
  },
  {
    id: "package",
    mark: "📦",
    name: "PACKAGE",
    category: "THING",
    meaning: "A bundled, movable Thing.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["package", "bundle", "artifact", "ship"],
  },
  {
    id: "document",
    mark: "📄",
    name: "DOCUMENT",
    category: "THING",
    meaning: "A written Thing.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["document", "pdf", "file", "page", "paper"],
  },
  {
    id: "database",
    mark: "🗄",
    name: "DATABASE",
    category: "THING",
    meaning: "A Thing that stores state.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["database", "db", "store", "data", "table"],
  },
  {
    id: "cube",
    mark: "🧊",
    name: "CUBE",
    category: "THING",
    meaning: "A 3D Thing — a model on the Stage.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["cube", "model", "3d", "mesh", "glb", "stl"],
  },
  {
    id: "song",
    mark: "🎵",
    name: "SONG",
    category: "THING",
    meaning: "An authored audio Thing.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["song", "music", "audio", "track"],
  },
  {
    id: "app",
    mark: "🖥",
    name: "APP",
    category: "THING",
    meaning: "A running application Thing.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["app", "application", "program", "software"],
  },

  // ── THREAD ──────────────────────────────────────────────────────────────
  {
    id: "thread",
    mark: "🧵",
    name: "THREAD",
    category: "THREAD",
    meaning: "A relationship tied between Things.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["thread", "relationship", "tie", "connection", "seam"],
  },
  {
    id: "link",
    mark: "🔗",
    name: "LINK",
    category: "THREAD",
    meaning: "A reference from one Thing to another.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["link", "url", "reference", "href"],
  },
  {
    id: "ada",
    mark: "❋",
    name: "ADA",
    category: "THREAD",
    meaning: "Composition — the language that weaves Things into fabric.",
    surfaces: ["RENDER"],
    keywords: ["ada", "composition", "weave", "loom", "pattern", "seam", "fabric"],
  },

  // ── ACTION ──────────────────────────────────────────────────────────────
  {
    id: "send",
    mark: "→",
    name: "SEND / NEXT",
    category: "ACTION",
    meaning: "Move forward — send, or advance to next.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["send", "next", "forward", "arrow", "go"],
  },
  {
    id: "return",
    mark: "←",
    name: "RETURN",
    category: "ACTION",
    meaning: "Go back to the previous state.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["return", "back", "previous", "arrow"],
  },
  {
    id: "leave-place",
    mark: "↗",
    name: "LEAVE PLACE",
    category: "ACTION",
    meaning: "Route change with Guardian relevance — a crossing shown on the map.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["leave", "crossing", "boundary", "route", "exit", "navigate"],
  },
  {
    id: "enter-place",
    mark: "↙",
    name: "ENTER PLACE",
    category: "ACTION",
    meaning: "Enter a place — a crossing inward shown on the map.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["enter", "into", "arrive", "route"],
  },
  {
    id: "exchange",
    mark: "⇄",
    name: "EXCHANGE",
    category: "ACTION",
    meaning: "Two-way exchange between Things.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["exchange", "swap", "sync", "trade", "two-way"],
  },
  {
    id: "retry",
    mark: "↻",
    name: "RETRY",
    category: "ACTION",
    meaning: "Attempt the same action again.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["retry", "again", "refresh", "loop"],
  },
  {
    id: "handoff",
    mark: "⇥",
    name: "HANDOFF",
    category: "ACTION",
    meaning: "Pass responsibility to the next holder.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["handoff", "pass", "delegate", "next"],
  },
  {
    id: "commit",
    mark: "📌",
    name: "COMMIT",
    category: "ACTION",
    meaning: "Fix a change into history.",
    surfaces: ["RENDER", "RECEIPT"],
    keywords: ["commit", "git", "github", "save", "pin"],
  },
  {
    id: "merge",
    mark: "🔀",
    name: "MERGE",
    category: "ACTION",
    meaning: "Join two lines of growth into one.",
    surfaces: ["RENDER"],
    keywords: ["merge", "git", "github", "join", "combine"],
  },
  {
    id: "fork",
    mark: "⑂",
    name: "FORK",
    category: "ACTION",
    meaning: "Split a new line of growth from a Thing.",
    surfaces: ["RENDER"],
    keywords: ["fork", "git", "github", "split", "branch off"],
  },

  // ── GUARDIAN ────────────────────────────────────────────────────────────
  {
    id: "guardian",
    mark: "◆",
    name: "GUARDIAN",
    category: "GUARDIAN",
    meaning: "A Guardian decision — the knot where authority is exercised.",
    surfaces: ["GUARDIAN", "RECEIPT"],
    keywords: ["guardian", "decision", "knot", "authority", "boundary", "gate"],
  },
  {
    id: "allow-once",
    mark: "◆",
    name: "ALLOW ONCE",
    category: "GUARDIAN",
    meaning: "A single-use grant, receipted. (Same mark as GUARDIAN — a decision value.)",
    surfaces: ["GUARDIAN", "RECEIPT"],
    keywords: ["allow", "grant", "once", "permit", "decision"],
  },
  {
    id: "block",
    mark: "⊘",
    name: "BLOCK",
    category: "GUARDIAN",
    meaning: "Denied by a Guardian — the crossing does not happen.",
    surfaces: ["GUARDIAN", "RECEIPT"],
    keywords: ["block", "deny", "boundary", "refuse", "no", "stop"],
  },
  {
    id: "escalate",
    mark: "⇱",
    name: "ESCALATE",
    category: "GUARDIAN",
    meaning: "Privilege change — always receipts. Never appears on a map.",
    surfaces: ["GUARDIAN", "RECEIPT"],
    keywords: ["escalate", "privilege", "elevate", "authority", "receipt"],
  },
  {
    id: "deny",
    mark: "×",
    name: "DENY",
    category: "GUARDIAN",
    meaning: "Refusal of a request.",
    surfaces: ["GUARDIAN", "RECEIPT"],
    keywords: ["deny", "no", "refuse", "cross", "reject"],
  },
  {
    id: "verified",
    mark: "✓",
    name: "VERIFIED",
    category: "GUARDIAN",
    meaning: "Attested true — a proof that holds.",
    surfaces: ["GUARDIAN", "RECEIPT"],
    keywords: ["verified", "check", "attest", "proof", "ok", "receipt"],
  },
  {
    id: "target",
    mark: "◎",
    name: "TARGET",
    category: "GUARDIAN",
    meaning: "The aim of a decision — what authority is being applied to.",
    surfaces: ["GUARDIAN", "RENDER"],
    keywords: ["target", "aim", "focus", "decision"],
  },
  {
    id: "guardian-enforced",
    mark: "🔒",
    name: "GUARDIAN-ENFORCED",
    category: "GUARDIAN",
    meaning: "Access gated by a Guardian. (Same mark as LOCKED PLACE — category disambiguates.)",
    surfaces: ["GUARDIAN", "RECEIPT"],
    keywords: ["locked", "enforced", "gated", "permission", "authority"],
  },
  {
    id: "sovereign",
    mark: "👑",
    name: "SOVEREIGN",
    category: "GUARDIAN",
    meaning: "Sovereignty — held only by humans. Providers never wear the crown.",
    surfaces: ["GUARDIAN", "RENDER"],
    keywords: ["crown", "sovereign", "authority", "owner", "king"],
  },
  {
    id: "eye",
    mark: "👁",
    name: "EYE",
    category: "GUARDIAN",
    meaning: "Observed — this is visible to a watcher.",
    surfaces: ["GUARDIAN", "RENDER"],
    keywords: ["eye", "watch", "visible", "observe", "see"],
  },
  {
    id: "hidden",
    mark: "🙈",
    name: "HIDDEN",
    category: "GUARDIAN",
    meaning: "Withheld from view.",
    surfaces: ["GUARDIAN", "RENDER"],
    keywords: ["hidden", "hide", "private", "masked"],
  },
  {
    id: "warning",
    mark: "⚠",
    name: "WARNING",
    category: "GUARDIAN",
    meaning: "Proceed with caution.",
    surfaces: ["GUARDIAN", "RENDER", "RECEIPT"],
    keywords: ["warning", "caution", "alert", "risk"],
  },
  {
    id: "question",
    mark: "?",
    name: "QUESTION",
    category: "GUARDIAN",
    meaning: "Unknown — a decision cannot yet be made.",
    surfaces: ["GUARDIAN", "RENDER"],
    keywords: ["question", "unknown", "help", "ask"],
  },

  // ── TRACE ───────────────────────────────────────────────────────────────
  {
    id: "trace",
    mark: "🕘",
    name: "TRACE",
    category: "TRACE",
    meaning: "Time — the record of what happened.",
    surfaces: ["RECEIPT", "RENDER"],
    keywords: ["trace", "time", "history", "log", "when"],
  },
  {
    id: "weight",
    mark: "⚖",
    name: "WEIGHT",
    category: "TRACE",
    meaning: "Memory as consequence — carried, not free.",
    surfaces: ["RECEIPT", "RENDER"],
    keywords: ["weight", "memory", "consequence", "mass"],
  },
  {
    id: "scar",
    mark: "※",
    name: "SCAR",
    category: "TRACE",
    meaning: "Evidence of a change that was survived.",
    surfaces: ["RECEIPT", "RENDER"],
    keywords: ["scar", "learning", "evidence", "mark", "wound"],
  },
  {
    id: "receipt",
    mark: "🧾",
    name: "RECEIPT",
    category: "TRACE",
    meaning: "A proof that an event occurred.",
    surfaces: ["RECEIPT", "RENDER"],
    keywords: ["receipt", "proof", "attest", "record", "stamp"],
  },
  {
    id: "hash",
    mark: "#",
    name: "HASH",
    category: "TRACE",
    meaning: "An identifier derived from content.",
    surfaces: ["RECEIPT", "RENDER"],
    keywords: ["hash", "id", "identify", "digest", "sha"],
  },

  // ── CONNECTOR ───────────────────────────────────────────────────────────
  {
    id: "talon",
    mark: "◇",
    name: "TALON",
    category: "CONNECTOR",
    meaning: "Capability carried by an agent — power without sovereignty.",
    surfaces: ["MAP", "RENDER", "RECEIPT"],
    keywords: ["talon", "capability", "agent", "carry", "claw"],
  },
  {
    id: "github",
    mark: "🐙",
    name: "GITHUB",
    category: "CONNECTOR",
    meaning: "A connector to GitHub — supplies capability, never sovereignty.",
    surfaces: ["MAP", "RENDER", "RECEIPT"],
    keywords: ["github", "git", "connector", "remote", "provider"],
  },
  {
    id: "reasoner",
    mark: "🧠",
    name: "REASONER",
    category: "CONNECTOR",
    meaning: "A model that can reason — a provider, never the human.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["ai", "model", "reason", "brain", "mind", "llm"],
  },
  {
    id: "cloud",
    mark: "☁",
    name: "CLOUD",
    category: "CONNECTOR",
    meaning: "A remote capability reached over a network.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["cloud", "remote", "sync", "server"],
  },
  {
    id: "api",
    mark: "🔌",
    name: "API",
    category: "CONNECTOR",
    meaning: "A pluggable capability interface.",
    surfaces: ["MAP", "RENDER"],
    keywords: ["api", "plug", "integration", "provider", "interface"],
  },
  {
    id: "mention",
    mark: "@",
    name: "MENTION",
    category: "CONNECTOR",
    meaning: "An address to a person or place.",
    surfaces: ["RENDER"],
    keywords: ["mention", "at", "address", "handle"],
  },
  {
    id: "bluetooth",
    mark: "ᛒ",
    name: "BLUETOOTH",
    category: "CONNECTOR",
    meaning: "A short-range pairing to a nearby device.",
    surfaces: ["RENDER"],
    keywords: ["bluetooth", "pair", "device", "wireless"],
  },

  // ── SYSTEM ──────────────────────────────────────────────────────────────
  {
    id: "settings",
    mark: "⚙",
    name: "SETTINGS",
    category: "SYSTEM",
    meaning: "Configuration of the system itself.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["settings", "config", "gear", "options", "preferences"],
  },
  {
    id: "terminal",
    mark: "⌨",
    name: "TERMINAL",
    category: "SYSTEM",
    meaning: "The Engine Room — direct command.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["terminal", "shell", "console", "command", "cli"],
  },
  {
    id: "code",
    mark: "</>",
    name: "CODE",
    category: "SYSTEM",
    meaning: "Source that enforces the law.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["code", "source", "dev", "html", "brackets"],
  },
  {
    id: "command",
    mark: "⌘",
    name: "COMMAND",
    category: "SYSTEM",
    meaning: "An issued system command.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["command", "cmd", "key", "run"],
  },
  {
    id: "clipboard",
    mark: "📋",
    name: "CLIPBOARD",
    category: "SYSTEM",
    meaning: "Held content awaiting placement.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["clipboard", "copy", "paste", "buffer"],
  },
  {
    id: "notification",
    mark: "🔔",
    name: "NOTIFICATION",
    category: "SYSTEM",
    meaning: "A system-raised signal for attention.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["notification", "bell", "alert", "signal"],
  },

  // ── LEXICON ─────────────────────────────────────────────────────────────
  {
    id: "dictionary",
    mark: "📖",
    name: "ICON//LEXICON",
    category: "LEXICON",
    meaning: "The representation layer of the constitution — this document.",
    surfaces: ["RENDER", "PICKER"],
    keywords: ["dictionary", "lexicon", "glyph", "mapping", "vocabulary", "index"],
  },
];
